config/routes.rb
AkiDemo::Application.routes.draw do

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact' 
  get 'admin' => 'matches#index'

  post 'matches/update'
  get 'matches/index'

  

end

app/models/match.rb
require 'csv'

class Match < ActiveRecord::Base

  def self.import_from_csv(file_path)

    CSV.foreach(Rails.root.join(file_path), headers: true) do |row|
      match_table = row[0].split(" ")

      Match.create(
        team1: match_table[0],
        team2: match_table[1],
        place: match_table[2],
        date: match_table[3],
        price: match_table[4]
        
      )

    end
  end

	def self.import
	    import_from_csv('csvs/match.csv')

  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  protect_from_forgery :except => :update

  before_filter :get_matches


  def index
    respond_to do |format|
      format.html
      format.json {
        render :json => {
          matches: @matches,
          today_matches: @today_matches
        }.to_json
      }
    end
  end

  def update
    match_params = params.permit(:id, :team1, :team2, :place, :date, :price)
    @match = Match.find(params[:id])
    @match.update_attributes!(match_params)

    render :json => {
      matches: @matches,
      today_matches: @today_matches
    }.to_json
  end

  def get_matches
    @matches = Match.where(date: 'none')
    @today_matches = Match.where(date: 'today')
  end  		

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Aki demo App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end	
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   <nav>    
    <%= link_to "Akí", root_path, id: "logo" %>
 
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Contact", contact_path %></li>        
        <li><%= link_to "About", about_path %></li>  
        <li><%= link_to "Admin", admin_path %></li>      
           
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            </a>
            <ul class="dropdown-menu">
              <li class="divider"></li>
              <li>
              </li>
            </ul>
          </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body ng-app="akiMain" ng-controller="MainCtrl">
    <%= render 'layouts/header' %>

	<%= yield %>


    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/matches/index.html.erb
  <br><br><br><br><br>
  <div role="tabpanel jumbotron">

  <!-- Nav tabs -->
  <ul class="center nav nav-tabs nav-tabs-admin" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">On Arrival</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">On Game</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">On departure</a></li>
  </ul>

  <!-- Tab panes -->
  <div class=" tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="home">

        <div class="jumbotron">
          <div class="container">
            <h3> Today's Game </h3>
            <div class="panel">
              <table class="table table-bordered">
                <thead>
                  <th>Team 1</th>
                  <th>Team 2</th>
                  <th>Place</th>
                  <th>Date </th>
                  <th>Price</th>    
                </thead>          
                <tr ng-repeat="match_t in today_matches | filter:myTeamFilter">
                  <td>{{ match_t.team1 }}</td> 
                  <td>{{ match_t.team2 }}</td>
                  <td>{{ match_t.place }}</td> 
                  <td>{{ match_t.date }}</td>
                  <td>{{ match_t.price }}</td> 
                  <td>

                    <span class="glyphicon glyphicon-remove-circle red" ng-click="noneMatch(match_t, 'none')"></span>
                  </td>            
                </tr>
              </table>
            </div>
          </div>
        </div>
          <div class="container">

          <div class="col-xs-6">
       <h3> Game Schedule</h3>            
            <div class="form-group">
              <input type="search" ng-model="search" placeholder="Match Search" class="form-control">
            </div>
          </div>

            <div class="container">
     

              <table class="table table-striped">
                <thead>
                  <th>Team 1</th>
                  <th>Team 2</th>
                  <th>Place</th>
                  <th>Date </th>
                  <th>Price</th>    
                </thead>
                <tr ng-repeat="match in matches | filter:positionFilter | filter:draftedFilter | filter:search">
                  <td>{{ match.team1 }}</td> 
                  <td>{{ match.team2 }}</td>
                  <td>{{ match.place }}</td> 
                  <td>{{ match.date }}</td>
                  <td>{{ match.price }}</td> 
                  <td>
                    <span class="glyphicon glyphicon-ok-circle green" ng-click="todayMatch(match, 'today')"></span>
                    &nbsp;

                  </td>
                </tr>
              </table>

            </div>

      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="profile">
      on game

    </div>
    <div role="tabpanel" class="tab-pane fade" id="messages">

      on departure
    </div>

  </div>

</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<br><br><br>
<div class="row well">
	<h3>On the nav bar</h3>
	<p>Home is a page containing simulation buttons (will be replaced in production as a signal from app to backend when a person arrive, order an item, leave the game ..... </p>
	 
	<h3>The admin page has three control panes to control what is going to be displayed on the home page</h3>
	<ol>
		<li>
			<h3>On arrival tab controls arrival scenario, consists of two tables.</h3>
			<p>Today’s games are games which are shown to users on arrival, game on this table is shown when the arrival button is clicked on the home page.</p>
			<p>The arrival button is a simulation button to communicate with the backend, but in production the button functionality should be replaced by a signal from the android app to the backend (When the smart phone is on the vicinity of the gate, beacon send a signal to the smart phone app (android or IOS), on detection the app should automatically ask the backend today’s game and related details (price, time, teams.....))</p>
			<p>Admins can control today’s game by using the control button on the right left most column of each button, click controls to assign today’s game</p>
		</li>
		<li>
			<h3>On Game tab controls on game scenario, consists of two tables.</h3>
		</li>
		<li>
			<h3>On Departure tab controls the departure scenario, consists of two tables.</h3>
		</li>


	<ol>        
 
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>



	<div class="center jumbotron">
		<h3><a href="http://aki.co/">Akí </a></h3>
	</div>
	
     

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron clearfix">

	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 init-boxes-container">
		<div class="init-boxes">
			<hr>			
			<h2 class = "btn btn-lg btn-primary btn-simul" data-toggle="modal" data-target="#arrival_Modal"> Arrival </h2>
			<hr>
		</div>

		<div class="init-boxes">
			<hr>			
			<h2 class=  "btn btn-lg btn-primary btn-simul"> On Game </h2>
			<hr>
		</div>
		<div class="init-boxes">
			<hr>			
			<h2 class=  "btn btn-lg btn-primary btn-simul"> Departure </h2>
			<hr>			
		</div>
	</div>
</div>
<div class="modal fade modal-fullscreen force-fullscreen" id="arrival_Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content modal-content-arrival">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Welcome to .........</h4>
      </div>
      <div class="modal-body">
	      <div class="panel panel-arrival">
	        <table class="table table-bordered">
	          <thead>
	            <th>Team 1</th>
	            <th>Team 2</th>
	            <th>Place</th>
	            <th>Date </th>
	            <th>Price</th>    
	          </thead>          
	          <tr ng-repeat="match_t in today_matches | filter:myTeamFilter">
	            <td>{{ match_t.team1 }}</td> 
	            <td>{{ match_t.team2 }}</td>
	            <td>{{ match_t.place }}</td> 
	            <td>{{ match_t.date }}</td>
	            <td><button type="button" class="btn btn-primary"  data-toggle="modal" data-target="#tank_you_Modal">{{ match_t.price }} NOK</button></td> 
	            <!--<td>

	              <span class="glyphicon glyphicon-remove-circle red" ng-click="noneMatch(match_t, 'none')"></span>
	            </td>    -->        
	          </tr>
	        </table>
	      </div>
      </div>
      <div class="modal-footer">
       <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>-->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade modal-fullscreen force-fullscreen" id="tank_you_Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <h4 class="modal-title"> Thank You! Enjoy the game </h4>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!--<button type="button" class="btn btn-primary">Save changes</button>-->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->